name: Build Release APK

on: 
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2  # Use v2 for the checkout action

    # 增加一步设置项目目录权限，确保后续操作有足够权限
    - name: Set project directory permissions
      run: |
        sudo chmod -R 777.
        echo "Set permissions for the project directory"

    - name: Setup JDK 17
      uses: actions/setup-java@v2  # Use v2 for the setup-java action
      with:
        java-version: 17  # Set the Java version to 17
        distribution: 'zulu'  # Use the Zulu JDK distribution

    # Configure signing properties directly in the file
    - name: Configure signing properties
      run: |
        if [! -d "android" ]; then
          mkdir android
          echo "Created android directory"
        fi
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" > android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
        echo "Successfully configured signing properties"

    # Decode keystore file and save it to the specified location
    - name: Decode keystore file
      run: |
        if [ -z "${{ secrets.KEY_STORE }}" ]; then
          echo "ERROR: KEY_STORE secret is empty"
          exit 1
        fi
        echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/app/key.jks
        echo "Successfully decoded keystore file"

    # Build the release APK using Gradle
    - name: Build with Gradle
      run: |
       ./gradlew assembleRelease || (echo "Gradle build failed, check the logs" && exit 1)
        echo "Successfully built the release APK"

    # Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3  # Use v3 for the upload-artifact action
      with:
        name: DDweather-release.apk
        path: app/build/outputs/apk/release/app-release.apk  # Path to the release APK

    # Create a release on GitHub and upload the APK to the release page
    
