name: Build Release APK

on: 
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2  # Use v2 for the checkout action

    - name: Setup JDK 17
      uses: actions/setup-java@v2  # Use v2 for the setup-java action
      with:
        java-version: 17  # Set the Java version to 17
        distribution: 'zulu'  # Use the Zulu JDK distribution

    # Configure signing properties directly in the file
    - name: Configure signing properties
      run: |
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" > android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties

    # Decode keystore file and save it to the specified location
    - name: Decode keystore file
      run: echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/app/key.jks

    # Build the release APK using Gradle
    - name: Build with Gradle
      run: ./gradlew assembleRelease  # Run the Gradle build command

    # Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3  # Use v3 for the upload-artifact action
      with:
        name: DDweather-release.apk
        path: app/build/outputs/apk/release/app-release.apk  # Path to the release APK
