name: Build Release APK

on: 
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Setup JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Setup Flutter environment
      uses: subosito/flutter-action@v2
      with:
        channel: "stable"

    - name: Configure signing properties
      run: |
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" > ${{ env.PROPERTIES_PATH }}
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> ${{ env.PROPERTIES_PATH }}
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> ${{ env.PROPERTIES_PATH }}

    - name: Decode keystore file
      run: echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/app/key.jks

    - name: Build with Gradle
      run: ./gradlew assembleRelease  # 构建 release 版本

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DDweather-release.apk
        path: app/build/outputs/apk/release/app-release.apk  # 上传 release 版本的 APK

    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'  # 仅在 master 分支上创建 release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"  # 设置 release 标签
        prerelease: false  # 设置为正式发布，不是预发布
        title: ${{ github.sha }}  # 使用当前 commit 的 SHA 作为 release 标题
        files: |
          app/build/outputs/apk/release/app-release.apk  # 上传 release 版本的 APK
